fullname: YOUR_PROJECT_NAME_GOES_HERE
slogan: Simpler blog example by the_shorekeeper using Nue.
credits: shouanren ~ the_shorekeeper
social:
  - icon: github
    url: https://github.com/shouanren/
  - icon: linkedin
    url: https://x.com/the_shorekeeper
